import { Button } from "@/components/ui/button";
import { useLocation } from "wouter";
import { useState } from "react";
import {
    Sparkles, ArrowRight, Globe, MonitorSmartphone, Star,
    MapPin, Phone, Clock, ChevronRight, Wrench, Zap
} from "lucide-react";

const demoSites = [
    {
        id: "plumber",
        name: "Prime Plumbing Co.",
        category: "Plumbing",
        location: "Austin, TX",
        color: "from-blue-600 to-cyan-500",
        phone: "(512) 555-0123",
        tagline: "24/7 Emergency Plumbing Services in Austin",
        services: ["Drain Cleaning", "Water Heater Repair", "Pipe Installation", "Emergency Service"],
    },
    {
        id: "dentist",
        name: "Bright Smile Dental",
        category: "Dentistry",
        location: "Los Angeles, CA",
        color: "from-teal-500 to-emerald-500",
        phone: "(310) 555-0456",
        tagline: "Family & Cosmetic Dentistry in LA",
        services: ["General Dentistry", "Teeth Whitening", "Invisalign", "Dental Implants"],
    },
    {
        id: "restaurant",
        name: "Bella Cucina",
        category: "Italian Restaurant",
        location: "New York, NY",
        color: "from-rose-600 to-orange-500",
        phone: "(212) 555-0789",
        tagline: "Authentic Italian Dining in Manhattan",
        services: ["Dine-In", "Catering", "Private Events", "Takeout & Delivery"],
    },
    {
        id: "law",
        name: "Morrison & Associates",
        category: "Law Firm",
        location: "Chicago, IL",
        color: "from-slate-700 to-slate-900",
        phone: "(312) 555-0321",
        tagline: "Trusted Legal Services Since 1998",
        services: ["Personal Injury", "Business Law", "Estate Planning", "Criminal Defense"],
    },
];

export default function DemoPage() {
    const [, setLocation] = useLocation();
    const [activeSite, setActiveSite] = useState(demoSites[0]);
    const [viewMode, setViewMode] = useState<"desktop" | "mobile">("desktop");

    return (
        <>
            {/* Hero */}
            <section className="relative pt-32 pb-16 px-4 sm:px-6 lg:px-8 overflow-hidden">
                <div className="absolute inset-0">
                    <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-[#7C3AED]/10 rounded-full blur-3xl animate-pulse" />
                    <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-[#7C3AED]/8 rounded-full blur-3xl animate-pulse" style={{ animationDelay: "1s" }} />
                </div>
                <div className="relative max-w-4xl mx-auto text-center">
                    <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight mb-6">
                        See SiteGenie{" "}
                        <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#7C3AED] to-[#F59E0B]">
                            In Action
                        </span>
                    </h1>
                    <p className="text-xl text-gray-400 max-w-2xl mx-auto leading-relaxed">
                        Explore sample websites generated by our AI. Each one was created in under 5 minutes
                        with zero coding.
                    </p>
                </div>
            </section>

            {/* Demo Selector */}
            <section className="py-8 px-4 sm:px-6 lg:px-8">
                <div className="max-w-6xl mx-auto">
                    {/* Category Tabs */}
                    <div className="flex flex-wrap gap-3 justify-center mb-8">
                        {demoSites.map((site) => (
                            <button
                                key={site.id}
                                onClick={() => setActiveSite(site)}
                                className={`px-5 py-2.5 rounded-full text-sm font-medium transition-all ${activeSite.id === site.id
                                        ? "bg-gradient-to-r from-[#7C3AED] to-[#F59E0B] text-white shadow-lg shadow-[#7C3AED]/25"
                                        : "bg-white/5 text-gray-400 hover:bg-white/10 hover:text-white border border-white/10"
                                    }`}
                            >
                                {site.category}
                            </button>
                        ))}
                    </div>

                    {/* View Mode Toggle */}
                    <div className="flex justify-center mb-6">
                        <div className="bg-white/5 border border-white/10 rounded-xl p-1 flex gap-1">
                            <button
                                onClick={() => setViewMode("desktop")}
                                className={`px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 transition-all ${viewMode === "desktop" ? "bg-white/10 text-white" : "text-gray-400 hover:text-white"
                                    }`}
                            >
                                <Globe className="h-4 w-4" /> Desktop
                            </button>
                            <button
                                onClick={() => setViewMode("mobile")}
                                className={`px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 transition-all ${viewMode === "mobile" ? "bg-white/10 text-white" : "text-gray-400 hover:text-white"
                                    }`}
                            >
                                <MonitorSmartphone className="h-4 w-4" /> Mobile
                            </button>
                        </div>
                    </div>

                    {/* Preview Window */}
                    <div className={`mx-auto transition-all duration-500 ${viewMode === "mobile" ? "max-w-sm" : "max-w-5xl"}`}>
                        <div className="rounded-2xl border border-white/10 overflow-hidden shadow-2xl shadow-black/30">
                            {/* Browser Chrome */}
                            <div className="bg-gray-800 px-4 py-3 flex items-center gap-3">
                                <div className="flex gap-2">
                                    <div className="w-3 h-3 rounded-full bg-red-500" />
                                    <div className="w-3 h-3 rounded-full bg-yellow-500" />
                                    <div className="w-3 h-3 rounded-full bg-green-500" />
                                </div>
                                <div className="flex-1 bg-gray-700 rounded-lg px-4 py-1.5 text-xs text-gray-400 font-mono">
                                    https://{activeSite.id}.SiteGenie.site
                                </div>
                            </div>

                            {/* Mock Website Content */}
                            <div className="bg-white text-gray-900">
                                {/* Nav */}
                                <div className={`bg-gradient-to-r ${activeSite.color} text-white px-6 py-4 flex items-center justify-between`}>
                                    <span className="font-bold text-lg">{activeSite.name}</span>
                                    <div className="hidden sm:flex gap-6 text-sm">
                                        <span className="opacity-80 hover:opacity-100 cursor-pointer">Home</span>
                                        <span className="opacity-80 hover:opacity-100 cursor-pointer">Services</span>
                                        <span className="opacity-80 hover:opacity-100 cursor-pointer">About</span>
                                        <span className="opacity-80 hover:opacity-100 cursor-pointer">Contact</span>
                                    </div>
                                    <div className="flex items-center gap-2 text-sm">
                                        <Phone className="h-4 w-4" />
                                        <span>{activeSite.phone}</span>
                                    </div>
                                </div>

                                {/* Hero */}
                                <div className={`bg-gradient-to-br ${activeSite.color} text-white px-8 py-16 text-center`}>
                                    <h2 className="text-3xl sm:text-4xl font-bold mb-4">{activeSite.tagline}</h2>
                                    <div className="flex items-center justify-center gap-2 text-sm opacity-80 mb-6">
                                        <MapPin className="h-4 w-4" />
                                        <span>{activeSite.location}</span>
                                        <span>•</span>
                                        <Clock className="h-4 w-4" />
                                        <span>Open 24/7</span>
                                    </div>
                                    <div className="flex gap-3 justify-center">
                                        <button className="bg-white text-gray-900 px-6 py-2.5 rounded-lg font-semibold text-sm">
                                            Get Free Quote
                                        </button>
                                        <button className="border border-white/30 px-6 py-2.5 rounded-lg text-sm">
                                            Call Now
                                        </button>
                                    </div>
                                    <div className="flex items-center justify-center gap-1 mt-6">
                                        {[...Array(5)].map((_, i) => (
                                            <Star key={i} className="h-4 w-4 fill-yellow-400 text-yellow-400" />
                                        ))}
                                        <span className="text-sm ml-2 opacity-80">4.9/5 from 120+ reviews</span>
                                    </div>
                                </div>

                                {/* Services */}
                                <div className="px-8 py-12">
                                    <h3 className="text-2xl font-bold text-center mb-8">Our Services</h3>
                                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                                        {activeSite.services.map((service) => (
                                            <div key={service} className="text-center p-4 rounded-xl bg-gray-50 border border-gray-100">
                                                <Wrench className="h-8 w-8 mx-auto mb-2 text-gray-400" />
                                                <p className="text-sm font-medium text-gray-700">{service}</p>
                                            </div>
                                        ))}
                                    </div>
                                </div>

                                {/* CTA */}
                                <div className="bg-gray-50 px-8 py-8 text-center border-t">
                                    <p className="text-gray-500 text-sm flex items-center justify-center gap-2">
                                        <Zap className="h-4 w-4" />
                                        Built with SiteGenie • AI-Generated Content • SEO Optimized
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* CTA */}
            <section className="py-24 px-4 sm:px-6 lg:px-8">
                <div className="max-w-4xl mx-auto text-center">
                    <h2 className="text-3xl sm:text-4xl font-bold mb-4">
                        Build Your Own Website Like This
                    </h2>
                    <p className="text-gray-400 max-w-xl mx-auto mb-8">
                        No coding needed. Just enter your business details, and our AI creates a professional,
                        SEO-optimized website in minutes.
                    </p>
                    <div className="flex flex-col sm:flex-row gap-4 justify-center">
                        <Button
                            size="lg"
                            onClick={() => setLocation("/dashboard/websites")}
                            className="bg-[#7C3AED] hover:bg-[#9333EA] text-black font-bold text-base px-8 py-6 rounded-xl shadow-lg shadow-[#7C3AED]/25"
                        >
                            <Sparkles className="mr-2 h-5 w-5" />
                            Start Building Free
                        </Button>
                        <Button
                            size="lg"
                            variant="outline"
                            onClick={() => setLocation("/features")}
                            className="text-base px-8 py-6 rounded-xl border-white/20 text-white hover:bg-white/5 bg-transparent"
                        >
                            Explore Features <ArrowRight className="ml-2 h-4 w-4" />
                        </Button>
                    </div>
                </div>
            </section>
        </>
    );
}
