import { Button } from "@/components/ui/button";
import { useLocation } from "wouter";
import { useState } from "react";
import {
    Sparkles, ArrowRight, Globe, MonitorSmartphone, ExternalLink
} from "lucide-react";

const demoSites = [
    {
        id: "water-damage",
        name: "Water Damage Restoration Austin TX",
        category: "Water Damage Restoration",
        location: "Austin, TX",
        url: "https://water-damage-restoration-austin-tx.netlify.app",
    },
];

export default function DemoPage() {
    const [, setLocation] = useLocation();
    const [activeSite, setActiveSite] = useState(demoSites[0]);
    const [viewMode, setViewMode] = useState<"desktop" | "mobile">("desktop");
    const [iframeLoading, setIframeLoading] = useState(true);

    return (
        <div className="min-h-screen bg-white">
            {/* Hero */}
            <section className="relative pt-32 pb-16 px-4 sm:px-6 lg:px-8 overflow-hidden bg-gradient-to-b from-purple-50 to-white">
                <div className="absolute inset-0">
                    <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-[#7C3AED]/8 rounded-full blur-3xl animate-pulse" />
                    <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-[#7C3AED]/6 rounded-full blur-3xl animate-pulse" style={{ animationDelay: "1s" }} />
                </div>
                <div className="relative max-w-4xl mx-auto text-center">
                    <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight mb-6 text-gray-900">
                        See SiteGenie{" "}
                        <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#7C3AED] to-[#F59E0B]">
                            In Action
                        </span>
                    </h1>
                    <p className="text-xl text-gray-600 max-w-2xl mx-auto leading-relaxed">
                        Explore real websites generated by our AI. Each one was created in under 5 minutes
                        with zero coding — and deployed live.
                    </p>
                </div>
            </section>

            {/* Demo Selector */}
            <section className="py-8 px-4 sm:px-6 lg:px-8">
                <div className="max-w-6xl mx-auto">
                    {/* Category Tabs */}
                    <div className="flex flex-wrap gap-3 justify-center mb-8">
                        {demoSites.map((site) => (
                            <button
                                key={site.id}
                                onClick={() => { setActiveSite(site); setIframeLoading(true); }}
                                className={`px-5 py-2.5 rounded-full text-sm font-medium transition-all ${activeSite.id === site.id
                                        ? "bg-gradient-to-r from-[#7C3AED] to-[#F59E0B] text-white shadow-lg shadow-[#7C3AED]/25"
                                        : "bg-gray-100 text-gray-600 hover:bg-gray-200 hover:text-gray-900 border border-gray-200"
                                    }`}
                            >
                                {site.category}
                            </button>
                        ))}
                    </div>

                    {/* View Mode Toggle + Visit Link */}
                    <div className="flex justify-center items-center gap-4 mb-6">
                        <div className="bg-gray-100 border border-gray-200 rounded-xl p-1 flex gap-1">
                            <button
                                onClick={() => setViewMode("desktop")}
                                className={`px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 transition-all ${viewMode === "desktop" ? "bg-white text-gray-900 shadow-sm" : "text-gray-500 hover:text-gray-900"
                                    }`}
                            >
                                <Globe className="h-4 w-4" /> Desktop
                            </button>
                            <button
                                onClick={() => setViewMode("mobile")}
                                className={`px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 transition-all ${viewMode === "mobile" ? "bg-white text-gray-900 shadow-sm" : "text-gray-500 hover:text-gray-900"
                                    }`}
                            >
                                <MonitorSmartphone className="h-4 w-4" /> Mobile
                            </button>
                        </div>
                        <a
                            href={activeSite.url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="inline-flex items-center gap-1.5 text-sm text-[#7C3AED] hover:text-[#9333EA] font-medium transition-colors"
                        >
                            Visit Live Site <ExternalLink className="h-3.5 w-3.5" />
                        </a>
                    </div>

                    {/* Preview Window — Real Iframe */}
                    <div className={`mx-auto transition-all duration-500 ${viewMode === "mobile" ? "max-w-sm" : "max-w-5xl"}`}>
                        <div className="rounded-2xl border border-gray-200 overflow-hidden shadow-xl">
                            {/* Browser Chrome */}
                            <div className="bg-gray-100 px-4 py-3 flex items-center gap-3 border-b border-gray-200">
                                <div className="flex gap-2">
                                    <div className="w-3 h-3 rounded-full bg-red-400" />
                                    <div className="w-3 h-3 rounded-full bg-yellow-400" />
                                    <div className="w-3 h-3 rounded-full bg-green-400" />
                                </div>
                                <div className="flex-1 bg-white rounded-lg px-4 py-1.5 text-xs text-gray-500 font-mono border border-gray-200">
                                    {activeSite.url}
                                </div>
                            </div>

                            {/* Live Website Iframe */}
                            <div className="relative bg-white" style={{ height: viewMode === "mobile" ? "600px" : "700px" }}>
                                {iframeLoading && (
                                    <div className="absolute inset-0 flex items-center justify-center bg-gray-50">
                                        <div className="text-center">
                                            <div className="w-8 h-8 border-3 border-[#7C3AED]/30 border-t-[#7C3AED] rounded-full animate-spin mx-auto mb-3" />
                                            <p className="text-sm text-gray-500">Loading {activeSite.name}...</p>
                                        </div>
                                    </div>
                                )}
                                <iframe
                                    key={activeSite.id}
                                    src={activeSite.url}
                                    title={`${activeSite.name} — Built with SiteGenie`}
                                    className="w-full h-full border-0"
                                    onLoad={() => setIframeLoading(false)}
                                    sandbox="allow-scripts allow-same-origin"
                                />
                            </div>
                        </div>
                    </div>

                    {/* Site Info */}
                    <div className="text-center mt-6">
                        <p className="text-sm text-gray-500">
                            <span className="font-medium text-gray-900">{activeSite.name}</span> — {activeSite.category} in {activeSite.location}
                        </p>
                    </div>
                </div>
            </section>

            {/* CTA */}
            <section className="py-24 px-4 sm:px-6 lg:px-8">
                <div className="max-w-4xl mx-auto text-center">
                    <h2 className="text-3xl sm:text-4xl font-bold mb-4 text-gray-900">
                        Build Your Own Website Like This
                    </h2>
                    <p className="text-gray-600 max-w-xl mx-auto mb-8">
                        No coding needed. Just enter your business details, and our AI creates a professional,
                        SEO-optimized website in minutes.
                    </p>
                    <div className="flex flex-col sm:flex-row gap-4 justify-center">
                        <Button
                            size="lg"
                            onClick={() => setLocation("/dashboard/websites")}
                            className="bg-[#7C3AED] hover:bg-[#9333EA] text-white font-bold text-base px-8 py-6 rounded-xl shadow-lg shadow-[#7C3AED]/25"
                        >
                            <Sparkles className="mr-2 h-5 w-5" />
                            Start Building Free
                        </Button>
                        <Button
                            size="lg"
                            variant="outline"
                            onClick={() => setLocation("/features")}
                            className="text-base px-8 py-6 rounded-xl border-gray-300 text-gray-900 hover:bg-gray-50 bg-transparent"
                        >
                            Explore Features <ArrowRight className="ml-2 h-4 w-4" />
                        </Button>
                    </div>
                </div>
            </section>
        </div>
    );
}
