import { Button } from "@/components/ui/button";
import { useLocation } from "wouter";
import {
    Sparkles, ArrowRight, Globe, ExternalLink, Check, MapPin, FileText, Search
} from "lucide-react";

export default function DemoPage() {
    const [, setLocation] = useLocation();

    return (
        <div className="min-h-screen bg-white">
            {/* Hero */}
            <section className="relative pt-32 pb-16 px-4 sm:px-6 lg:px-8 overflow-hidden bg-gradient-to-b from-purple-50 to-white">
                <div className="absolute inset-0">
                    <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-[#7C3AED]/8 rounded-full blur-3xl animate-pulse" />
                    <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-[#7C3AED]/6 rounded-full blur-3xl animate-pulse" style={{ animationDelay: "1s" }} />
                </div>
                <div className="relative max-w-4xl mx-auto text-center">
                    <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight mb-6 text-gray-900">
                        See SiteGenie{" "}
                        <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#7C3AED] to-[#F59E0B]">
                            In Action
                        </span>
                    </h1>
                    <p className="text-xl text-gray-600 max-w-2xl mx-auto leading-relaxed">
                        Explore a real website generated by our AI. Created in under 5 minutes
                        with zero coding — and deployed live on Netlify.
                    </p>
                </div>
            </section>

            {/* Live Website Showcase */}
            <section className="py-12 px-4 sm:px-6 lg:px-8">
                <div className="max-w-5xl mx-auto">
                    {/* Main demo card */}
                    <a
                        href="https://water-damage-restoration-austin-tx.netlify.app"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="block group"
                    >
                        <div className="rounded-2xl border border-gray-200 bg-white overflow-hidden shadow-xl transition-all group-hover:shadow-2xl group-hover:border-purple-200 group-hover:-translate-y-1">
                            {/* Browser chrome */}
                            <div className="bg-gray-100 px-4 py-3 flex items-center gap-3 border-b border-gray-200">
                                <div className="flex gap-2">
                                    <div className="w-3 h-3 rounded-full bg-red-400" />
                                    <div className="w-3 h-3 rounded-full bg-yellow-400" />
                                    <div className="w-3 h-3 rounded-full bg-green-400" />
                                </div>
                                <div className="flex-1 bg-white rounded-lg px-4 py-1.5 text-xs text-gray-500 font-mono border border-gray-200">
                                    https://water-damage-restoration-austin-tx.netlify.app
                                </div>
                                <ExternalLink className="h-4 w-4 text-gray-400 group-hover:text-[#7C3AED] transition-colors" />
                            </div>

                            {/* Website preview content */}
                            <div className="relative bg-gradient-to-br from-blue-50 via-white to-purple-50 p-12 sm:p-20 text-center">
                                <div className="mb-8">
                                    <Globe className="h-20 w-20 text-[#7C3AED]/30 mx-auto" />
                                </div>
                                <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4">
                                    Water Damage Restoration — Austin TX
                                </h2>
                                <p className="text-gray-500 mb-8 max-w-xl mx-auto text-lg">
                                    A complete, multi-page website with SEO optimization, schema markup, service pages, location pages, and more — all generated by AI.
                                </p>

                                <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 max-w-2xl mx-auto mb-10">
                                    {[
                                        { icon: FileText, label: "10+ Pages", color: "emerald" },
                                        { icon: Search, label: "Full SEO", color: "blue" },
                                        { icon: Globe, label: "Live on Netlify", color: "purple" },
                                        { icon: MapPin, label: "Local SEO", color: "amber" },
                                    ].map((item) => {
                                        const Icon = item.icon;
                                        return (
                                            <div key={item.label} className="flex flex-col items-center gap-2 p-3 rounded-xl bg-white border border-gray-200 shadow-sm">
                                                <Icon className={`h-5 w-5 text-${item.color}-600`} />
                                                <span className="text-xs font-medium text-gray-700">{item.label}</span>
                                            </div>
                                        );
                                    })}
                                </div>

                                <div className="inline-flex items-center gap-2 px-8 py-4 rounded-xl bg-[#7C3AED] text-white font-bold text-base shadow-lg shadow-[#7C3AED]/25 group-hover:bg-[#9333EA] transition-colors">
                                    <Globe className="h-5 w-5" />
                                    View Live Website
                                    <ExternalLink className="h-4 w-4 ml-1" />
                                </div>
                            </div>
                        </div>
                    </a>

                    {/* What's included in this site */}
                    <div className="mt-12 grid sm:grid-cols-3 gap-6">
                        <div className="rounded-xl border border-gray-200 bg-white shadow-sm p-6">
                            <h3 className="font-bold text-gray-900 mb-3">Pages Generated</h3>
                            <ul className="space-y-2 text-sm text-gray-600">
                                {["Homepage (2000+ words)", "Service pages", "Location pages", "About Us", "Contact page", "FAQ page (30+ questions)", "Privacy & Terms"].map(t => (
                                    <li key={t} className="flex items-center gap-2"><Check className="h-4 w-4 text-emerald-500 shrink-0" />{t}</li>
                                ))}
                            </ul>
                        </div>
                        <div className="rounded-xl border border-gray-200 bg-white shadow-sm p-6">
                            <h3 className="font-bold text-gray-900 mb-3">SEO Features</h3>
                            <ul className="space-y-2 text-sm text-gray-600">
                                {["Schema markup (JSON-LD)", "Meta titles & descriptions", "Open Graph tags", "Sitemap.xml", "Robots.txt", "Canonical URLs", "Heading hierarchy (H1→H3)"].map(t => (
                                    <li key={t} className="flex items-center gap-2"><Check className="h-4 w-4 text-blue-500 shrink-0" />{t}</li>
                                ))}
                            </ul>
                        </div>
                        <div className="rounded-xl border border-gray-200 bg-white shadow-sm p-6">
                            <h3 className="font-bold text-gray-900 mb-3">Technical Details</h3>
                            <ul className="space-y-2 text-sm text-gray-600">
                                {["Static HTML/CSS (fast)", "Mobile responsive", "Free SSL certificate", "Global CDN via Netlify", "Custom domain ready", "Google Maps embed", "Click-to-call CTAs"].map(t => (
                                    <li key={t} className="flex items-center gap-2"><Check className="h-4 w-4 text-purple-500 shrink-0" />{t}</li>
                                ))}
                            </ul>
                        </div>
                    </div>
                </div>
            </section>

            {/* CTA */}
            <section className="py-24 px-4 sm:px-6 lg:px-8">
                <div className="max-w-4xl mx-auto text-center">
                    <h2 className="text-3xl sm:text-4xl font-bold mb-4 text-gray-900">
                        Build Your Own Website Like This
                    </h2>
                    <p className="text-gray-600 max-w-xl mx-auto mb-8">
                        No coding needed. Just enter your business details, and our AI creates a professional,
                        SEO-optimized website in minutes.
                    </p>
                    <div className="flex flex-col sm:flex-row gap-4 justify-center">
                        <Button
                            size="lg"
                            onClick={() => setLocation("/dashboard/websites")}
                            className="bg-[#7C3AED] hover:bg-[#9333EA] text-white font-bold text-base px-8 py-6 rounded-xl shadow-lg shadow-[#7C3AED]/25"
                        >
                            <Sparkles className="mr-2 h-5 w-5" />
                            Start Building Free
                        </Button>
                        <Button
                            size="lg"
                            variant="outline"
                            onClick={() => setLocation("/features")}
                            className="text-base px-8 py-6 rounded-xl border-gray-300 text-gray-900 hover:bg-gray-50 bg-transparent"
                        >
                            Explore Features <ArrowRight className="ml-2 h-4 w-4" />
                        </Button>
                    </div>
                </div>
            </section>
        </div>
    );
}
